-- MySQL Script generated by MySQL Workbench
-- Wed May 10 15:36:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Balance` (
  `BalanceId` INT NOT NULL AUTO_INCREMENT,
  `BalanceAmount` INT NOT NULL,
  `BalanceDate` DATE NOT NULL,
  PRIMARY KEY (`BalanceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calender` (
  `CalenderId` INT NOT NULL,
  PRIMARY KEY (`CalenderId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `SurName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `EMail` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Balance_BalanceId` INT NOT NULL,
  `Calender_CalenderId` INT NOT NULL,
  PRIMARY KEY (`UserId`),
  INDEX `fk_User_Balance1_idx` (`Balance_BalanceId` ASC) VISIBLE,
  INDEX `fk_User_Calender1_idx` (`Calender_CalenderId` ASC) VISIBLE,
  CONSTRAINT `fk_User_Balance1`
    FOREIGN KEY (`Balance_BalanceId`)
    REFERENCES `mydb`.`Balance` (`BalanceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Calender1`
    FOREIGN KEY (`Calender_CalenderId`)
    REFERENCES `mydb`.`Calender` (`CalenderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransactionType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransactionType` (
  `TransactioneId` INT NOT NULL AUTO_INCREMENT,
  `TransactionType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TransactioneId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colour` (
  `Colour` INT NOT NULL AUTO_INCREMENT,
  `ColourName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Colour`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `TransactionId` INT NOT NULL AUTO_INCREMENT,
  `TransactionAmount` VARCHAR(45) NOT NULL,
  `TransactionDate` VARCHAR(45) NOT NULL,
  `TransactionType_TransactioneId` INT NOT NULL,
  `Balance_BalanceId` INT NOT NULL,
  PRIMARY KEY (`TransactionId`),
  INDEX `fk_Transaction_TransactionType1_idx` (`TransactionType_TransactioneId` ASC) VISIBLE,
  INDEX `fk_Transaction_Balance1_idx` (`Balance_BalanceId` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction_TransactionType1`
    FOREIGN KEY (`TransactionType_TransactioneId`)
    REFERENCES `mydb`.`TransactionType` (`TransactioneId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Balance1`
    FOREIGN KEY (`Balance_BalanceId`)
    REFERENCES `mydb`.`Balance` (`BalanceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CalenderEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CalenderEvent` (
  `CalenderEventId` INT NOT NULL AUTO_INCREMENT,
  `Text` VARCHAR(45) NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `Amount` VARCHAR(45) NOT NULL,
  `Calender_CalenderId` INT NOT NULL,
  `Colour_Colour` INT NOT NULL,
  `Transaction_TransactionId` INT NOT NULL,
  PRIMARY KEY (`CalenderEventId`),
  INDEX `fk_CalenderEvent_Calender1_idx` (`Calender_CalenderId` ASC) VISIBLE,
  INDEX `fk_CalenderEvent_Colour1_idx` (`Colour_Colour` ASC) VISIBLE,
  INDEX `fk_CalenderEvent_Transaction1_idx` (`Transaction_TransactionId` ASC) VISIBLE,
  CONSTRAINT `fk_CalenderEvent_Calender1`
    FOREIGN KEY (`Calender_CalenderId`)
    REFERENCES `mydb`.`Calender` (`CalenderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CalenderEvent_Colour1`
    FOREIGN KEY (`Colour_Colour`)
    REFERENCES `mydb`.`Colour` (`Colour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CalenderEvent_Transaction1`
    FOREIGN KEY (`Transaction_TransactionId`)
    REFERENCES `mydb`.`Transaction` (`TransactionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
